### ISSUE TITLE
Interactive issue

### ISSUE THREAD

**Issue by emilydinan** [huangyanzhou163/ConvAI#5]
Edit: resolved

**Comment by huangyanzhou163** [comment]
As our proposed model in the first round evaluation is a ranking model instead of a generative model, it will take a very long time to do the ranking for the human interaction in the second round evaluation if the questions are coming from the whole training set. To overcome this problem, we take advantage of the annoy package to retrieve the top 500 queries from the given training set for our ranking model. By doing so, our ranking model only need to rank 500 queries and thus the response time for each interaction is acceptable.
At present, the files in the github are updated accordingly. Please fetch the files from our github and refer the detailed description of "How to Run" in README.md. Notice that the data.tar.gz0, data.tar.gz1 and data.tar.gz2 are no longer in our github because of our limited space in github. You can still use the previous downloaded ones. 
If you encounter any problem, please let me know.

**Comment by huangyanzhou163** [comment]
As our proposed model in the first round evaluation is a ranking model instead of a generative model, it will take a very long time to do the ranking for the human interaction in the second round evaluation if the questions are coming from the whole training set. To overcome this problem, we take advantage of the annoy package to retrieve the top 500 queries from the given training set for our ranking model. By doing so, our ranking model only need to rank 500 queries and thus the response time for each interaction is acceptable.

Right now the files in our github are updated accordingly. Please fetch the files from github and refer to “How to Run” in README.md. Notice that the files data.tar.gz0, data.tar.gz1 and data.tar.gz2 are no longer in our github because of the limited space in github. These three files are not changed and you can use your previous downloaded ones. 
Please let me know if you have other question.

**Comment by huangyanzhou163** [comment]
As our proposed model in the first round evaluation is a ranking model instead of a generative model, it will take a very long time to do the ranking for the human interaction in the second round evaluation if the questions are coming from the whole training set. To overcome this problem, we take advantage of the annoy package to retrieve the top 500 queries from the given training set for our ranking model. By doing so, our ranking model only need to rank 500 queries and thus the response time for each interaction is acceptable.

Right now the files in our github are updated accordingly. Please fetch the files from github and refer to “How to Run” in README.md. Notice that the files data.tar.gz0, data.tar.gz1 and data.tar.gz2 are no longer in our github because of the limited space in github. These three files are not changed and you can use your previous downloaded ones. 

Please let me know if you have other question.

**Comment by huangyanzhou163** [comment]
We update the Vsmn.zip and prepare4eval.sh in the Github.
To make sure you run the same environment with us, please
download ParlAI: git clone https://github.com/facebookresearch/ParlAI.git
install annoy package: pip install annoy==1.13.0

We run our code successfully and one picture is also added in the Github.

**Comment by emilydinan** [comment]
Thank you, it's fixed!
